name: gymble_flutter
description: "A gym management application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  intl: ^0.18.1
  # mongo_dart dependency removed as it's not needed with API service
  flutter_secure_storage: ^8.0.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.4.1
  google_fonts: ^5.1.0
  # Added for auth requirements
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.1.6
  dropdown_button2: ^2.3.8
  flutter_dotenv: ^5.1.0
  # Added for location services
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env
